"""
Train an AE on the **varied-seed** z2gauge datasets.

Unlike every other z2gauge data file (which pins a single ITE initial state
PRNGKey(0) so every sample lands on the SAME Z2 twin), the varied-seed files
draw v_0 independently per sample. In the (quasi-)degenerate Z2 ground
subspace at small |h|, that means samples scatter across the 4-fold
topological ground manifold instead of all collapsing to one twin. This AE
lets us study how the latent geometry changes when twin selection is no
longer uniform across the sample set.

Data files (post-fix sign convention, generated by generate_variedseed_data.py):
    data_ite_confined_2x3_h-1.5_to_-0.7_n500_variedseed.pkl     (500 confined)
    data_ite_deconfined_2x3_h-0.15_to_-0.1_n500_variedseed.pkl  (500 deconfined)

Output:
    z2gauge_ite_autoencoder_variedseed_Lx2Ly3.pkl

Architecture / hyperparameters are taken from the current AEConfig the same
way main_active_phase.py builds them: layer_widths rebuilt from
D_in = 2^(2*Lx*Ly) while preserving hidden_dim and latent_dim from the
default tuple -> (D_in, 500, 30, 500, D_in). seed=83948, epochs=50000,
lr=1e-4, dropout=0.1, center_coeff=1e-3. This matches the active-phase
experiments exactly so the resulting AE is directly comparable.

Usage:
    cd z2gauge/scripts && python main_train_variedseed_ae.py
    LX=2 LY=3 python main_train_variedseed_ae.py        # same as default
"""
import os, sys, pickle
from dataclasses import replace

import numpy as np
import jax
import jax.numpy as jnp

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from configs.config import AEConfig
from models.autoencoder import init_params, fetch_latent
from training.ae_train import train_autoencoder
from utils.io import save_pickle, timestamp


# ── tunables (env-var overridable) ────────────────────────────────────────────
Lx = int(os.environ.get('LX', 2))
Ly = int(os.environ.get('LY', 3))
SEED = int(os.environ.get('SEED', AEConfig().seed))
N = 2 * Lx * Ly
D = 2 ** N

CONF_PATH = os.environ.get(
    'CONF_DATA',
    f'../data/data_ite_confined_{Lx}x{Ly}_h-1.5_to_-0.7_n500_variedseed.pkl')
DEC_PATH = os.environ.get(
    'DEC_DATA',
    f'../data/data_ite_deconfined_{Lx}x{Ly}_h-0.15_to_-0.1_n500_variedseed.pkl')

print(f'Lattice {Lx}x{Ly}  (N={N} qubits, D_in={D})')
print(f'Confined data:   {CONF_PATH}')
print(f'Deconfined data: {DEC_PATH}')

# ── load and stack ───────────────────────────────────────────────────────────
with open(CONF_PATH, 'rb') as f:
    data_conf = pickle.load(f)
with open(DEC_PATH, 'rb') as f:
    data_dec = pickle.load(f)

X_conf = np.array([d['v'].real for d in data_conf], dtype=np.float32)
X_dec  = np.array([d['v'].real for d in data_dec], dtype=np.float32)

h_conf = np.array([float(d['h']) for d in data_conf])
h_dec  = np.array([float(d['h']) for d in data_dec])

print(f'  confined  : {X_conf.shape}, h ∈ [{h_conf.min():+.4f}, {h_conf.max():+.4f}]')
print(f'  deconfined: {X_dec.shape}, h ∈ [{h_dec.min():+.4f}, {h_dec.max():+.4f}]')

X_all = np.concatenate([X_conf, X_dec], axis=0)
phase_all = np.array(['confined']*len(X_conf) + ['deconfined']*len(X_dec))

# Shuffle so SGD doesn't see the two phases sequentially.
rng = np.random.default_rng(SEED)
perm = rng.permutation(len(X_all))
X_all_s = X_all[perm]
phase_all_s = phase_all[perm]

print(f'Combined training set: {X_all_s.shape}')

# ── AE config + train ────────────────────────────────────────────────────────
ae_cfg = AEConfig()
hidden_dim = ae_cfg.layer_widths[1]
latent_dim = ae_cfg.layer_widths[2]
ae_cfg = replace(ae_cfg, layer_widths=(D, hidden_dim, latent_dim, hidden_dim, D))
print(f'AE layer widths: {ae_cfg.layer_widths}')
print(f'AE epochs={ae_cfg.epochs}, lr={ae_cfg.lr}, dropout={ae_cfg.dropout_p}, '
      f'center_coeff={ae_cfg.center_coeff}, seed={SEED}')

key = jax.random.PRNGKey(SEED)
key, sub = jax.random.split(key)
params = init_params(list(ae_cfg.layer_widths), sub, scale=ae_cfg.init_scale)

hist = train_autoencoder(
    params,
    X_all_s,
    epochs=ae_cfg.epochs,
    lr=ae_cfg.lr,
    drop_p=ae_cfg.dropout_p,
    center_coeff=ae_cfg.center_coeff,
    seed=SEED,
    log_every=ae_cfg.log_every,
    eval_every=ae_cfg.eval_every,
)
trained = hist['params']

# Save: AE params + centroid (mean of soft-normalized latents over training set)
Z = fetch_latent(trained, X_all_s, jax.random.PRNGKey(0))
centroid = jnp.mean(Z, axis=0)

out_path = f'../models/z2gauge_ite_autoencoder_variedseed_Lx{Lx}Ly{Ly}.pkl'
save_pickle({'params': trained, 'centroid': np.array(centroid)}, out_path)
print(f'Saved varied-seed AE to {out_path}')
